AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Name: Darren Foley
  Email: darrenfoley015@gmail.com
  Desc: Parent Template configuration which calls the project substacks.

# Parameters:
#   EnvironmentType:
#     Description: Type of environment
#     Type: 'AWS::SSM::Parameter::Value<String>'
#     Default: '/TEST'

#   EnvironmentName:
#     Description: Unique Identifier for project environment
#     Type: 'AWS::SSM::Parameter::Value<String>'
#     Default: '/TEST/EnvironmentName'

Resources:

  ParamModule:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./substacks/variables.yml
      Parameters: ./project-parameters.json
  
  ServiceModule:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./substacks/services.yml
    DependsOn: ParamModule

  NetworkModule:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./substacks/network.yml
    DependsOn: ParamModule

  ServerModule:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./substacks/servers.yml
    DependsOn: NetworkModule
  
  # DatabaseModule:
  #   Type: AWS::CloudFormation::Stack
  #     Properties:
  #       TemplateURL: ./substacks/servers.yml
  #     DependsOn: ServerModule

  

    
