AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Name: Darren Foley
  Email: darrenfoley015@gmail.com
  Desc: Template for creating EC2 launch configuration, Load balancer and Security Groups.

Parameters:

  EnvironmentType:
    Description: Type of environment
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/TEST'

  EnvironmentName:
    Description: Unique Identifier for project environment
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/TEST/EnvironmentName'
  
  UbuntuAMI:
    Description: Ubuntu AMI ID used for EC2 instances
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/canonical/ubuntu/server/18.04/stable/current/amd64/hvm/ebs-gp2/ami-id' 

  InstanceType:
    Description: Size of EC2 instances being used
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/TEST/EC2/InstanceType'

  InstanceDefaultPort:
    Description: Default port being used for EC2 instances
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/TEST/EC2/InstanceDefaultPort'
  
  InstanceDeviceName:
    Description: Device path name
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/TEST/EC2/InstanceDeviceName'
  
  InstanceVolumeSize:
    Description: Instance Volume size
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/TEST/EC2/InstanceVolumeSize'

  InstanceKeyPair:
    Description: Instance key pair name
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/TEST/EC2/InstanceKeyPair'

  AutoScalingMinSize:
    Description: Min size for autoscaling
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/TEST/EC2/Autoscaling/AutoScalingMinSize'
  
  AutoScalingMaxSize:
    Description: Max size for autoscaling
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/TEST/EC2/Autoscaling/AutoScalingMaxSize'

  CodeBucketName:
    Description: Name of Code bucket were project code will be pushed
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/TEST/CodeBucketName'

  UdagramS3Role:
    Description: Role used for interacting with S3
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/TEST/EC2/InstanceProfile/UdagramS3Role'

Resources:

  ProfileWithRolesForWebApp:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Roles:
        - !Ref UdagramS3Role

  LBSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to our load balancer
      VpcId:
        Fn::ImportValue:
          !Sub '${EnvironmentName}-${EnvironmentType}-VPCID'
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0

  WebServerSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to our hosts and SSH from local only
      VpcId:
        Fn::ImportValue:
          !Sub '${EnvironmentName}-${EnvironmentType}-VPCID'
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0

  WebAppLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update -y
          apt-get install awscli -y
          apt-get install apache2 -y
          systemctl start apache2.service
          aws s3 cp s3://${CodeBucketName}/src/index.html /var/www/html/ 
      ImageId: !Ref UbuntuAMI
      KeyName: !Ref InstanceKeyPair
      IamInstanceProfile: !Ref UdagramS3Role
      SecurityGroups:
      - Ref: WebServerSecGroup
      InstanceType: !Ref InstanceType
      BlockDeviceMappings:
      - DeviceName: !Ref InstanceDeviceName
        Ebs:
          VolumeSize: !Ref InstanceVolumeSize

  WebAppGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
      - Fn::ImportValue: 
          !Sub '${EnvironmentName}-${EnvironmentType}-PRIV-NETS'
      LaunchConfigurationName:
        Ref: WebAppLaunchConfig
      MinSize: !Ref AutoScalingMinSize
      MaxSize: !Ref AutoScalingMaxSize
      TargetGroupARNs:
      - Ref: WebAppTargetGroup

  WebAppLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
      - Fn::ImportValue: !Sub '${EnvironmentName}-${EnvironmentType}-PUB1-ID'
      - Fn::ImportValue: !Sub '${EnvironmentName}-${EnvironmentType}-PUB2-ID'
      SecurityGroups:
      - Ref: LBSecGroup

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
      - Type: forward
        TargetGroupArn:
          Ref: WebAppTargetGroup
      LoadBalancerArn:
        Ref: WebAppLB
      Port: '80'
      Protocol: HTTP

  ALBListenerRule:
      Type: AWS::ElasticLoadBalancingV2::ListenerRule
      Properties:
        Actions:
        - Type: forward
          TargetGroupArn: !Ref 'WebAppTargetGroup'
        Conditions:
        - Field: path-pattern
          Values: [/]
        ListenerArn: !Ref 'Listener'
        Priority: 1

  WebAppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 8
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 5
      VpcId: 
        Fn::ImportValue:
          Fn::Sub: '${EnvironmentName}-${EnvironmentType}-VPCID'


Outputs:
  LoadBalancerURL:
    Description: Export of Load Balancer URL
    Value: Fn::Join: ["", [ "http://", !GetAtt [ WebAppLB , DNSName] ] ]
    Export:
      Name: !Sub "${EnvironmentName}-${EnvironmentType}-DNSName"
